### PR TITLE
Fix typo in documentation (actually in comments)

### PR DESCRIPTION
**Pull request by Gluttton**

### CODE REVIEW

**Comment by Gluttton** [comment]
Some update.

I found the same word in the examples and realized that "antennae" is a valid English word. So, probably my fix is wrong.
```
$ grep -n antennae src/examples/singleRX.cpp 
74:                                    //Alternatively, NULL can be passed to LMS_GetAntennaList() to obtain number of antennae
78:    cout << "Available antennae:\n";            //print available antennae names
```

**Comment by 9600** [comment]
@Gluttton It is generally said that antennae is for biology only and here it would be antennas, but seems that may not be a firm position:

https://en.wikipedia.org/wiki/Wikipedia:Plural_of_antenna

The other typo looks more important.

**Comment by Gluttton** [comment]
@9600 thank you for the feedback and provided link. I thought that "antennae" is jargon, but based on the article this is a correct word.

Eventually, I've updated the patch and removed the fix related to the "antennae".

**Comment by gracid** [comment]
Hello,
Regarding the change of data type, the samples should be stored in int16 data type with the specified range. Otherwise if you decide to pack the samples yourself before passing them to LMS_UploadWFM, they will be compressed _again_ by Samples2FPGAPacketPayload.

**Comment by Gluttton** [comment]
Hello @gracid ,

Thank you for the clarification. I've removed the changes related to the data type.

**Pull request merged**
