### PR TITLE
Allow settings external reference clock from Soapy

### PR DESCRIPTION
**Pull request by herlesupreeth**
This PR facilitates setting of external clock reference freq. from Soapy.

### CODE REVIEW

**Comment by Mixaill** [comment]
It looks like

* `listClockSources`
* `setClockSource`
* `getClockSource` 

should also be implemented

**Comment by herlesupreeth** [comment]
@Mixaill the problem with those is that its not trivial to implement them as LimeSDR has many clocks.

**Comment by Mixaill** [comment]
@herlesupreeth 

On the first iteration it might be something like this. 
At least it gives information that the device has two different modes for the reference clock.

```cpp

// API
std::string getClockSource(void) const {
    return _clockExternal ? "external" : "internal";
}

double getReferenceClockRate(void) const {
    return _clockExternal ? _clockRate : 0.0;
}

RangeList getReferenceClockRates(void) const {
    RangeList result;
    result.push_back(Range(0, 300'000'000.0)); //200 MHz for LMK00105,  300 MHz for ADF4002
    return results;
}

std::vector<std::string> listClockSources(void) const {
    return {"internal", "external"};
}

void setClockSource(const std::string &source) {
   _clockExternal= source == "external";
   updateReferenceClock();
}

void setReferenceClockRate(const double rate) {
   _clockRate = std::max(0.0, rate);
   updateReferenceClock();
}



// PRIVATE
bool _clockExternal{false};
double _clockRate{10_000_000.};

void updateReferenceClock(){
    std::unique_lock<std::recursive_mutex> lock(_accessMutex);
    lms7Device->SetClockFreq(LMS_CLOCK_EXTREF, _clockExternal ? _clockRate : 0.0);
}


// USAGE
device->setReferenceClockRate(10_000_000);
device->setClockSource("external");
```

**Comment by ncorgan** [comment]
@herlesupreeth 

I like @Mixaill's additions. For the sake of symmetry/thoroughness, could you pull those in and validate it? Then we'd have a full good merge.

**Comment by herlesupreeth** [comment]
@ncorgan thanks for the feedback. Will do that and update the PR

**Comment by herlesupreeth** [comment]
@Mixaill thanks for your code

@ncorgan @Mixaill can you please review the PR once again

**Comment by ncorgan** [comment]
@9600 Tested locally, looks good to me.

**Comment by 9600** [comment]
@ncorgan Thanks! If you'd like to merge.

**Pull request merged**
